{{- if .Values.config }}
apiVersion: v1
kind: {{ if .Values.secretConfig -}} Secret {{- else -}} ConfigMap {{- end }}
metadata:
  name: {{ template "prometheus-mikrotik-exporter.fullname" . }}
  labels:
    {{- include "prometheus-mikrotik-exporter.labels" . | indent 4 }}
{{ if .Values.secretConfig -}} stringData: {{- else -}} data: {{- end }}
  mikrotik.yaml: |
{{ toYaml .Values.config | indent 4 }}
{{- end }}
